
import React, { useState, useEffect } from 'react';
import { useData } from '../src/shared/contexts/DataContext';
import { 
  BarChart3, 
  TrendingUp, 
  TrendingDown, 
  AlertCircle, 
  CheckCircle2, 
  Wheat, 
  Package, 
  ArrowRightLeft,
  Scale,
  RefreshCw,
  Clock,
  Plus,
  Trash2,
  X
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { getActiveBatch, saveProductionEntry } from '../firebase';
import { Batch } from '../types';
import { Toast, ToastType } from './Toast';

interface IndustrialControlViewProps {
  onBack: () => void;
}

export const IndustrialControlView: React.FC<IndustrialControlViewProps> = ({ onBack }) => {
  const { stock, wheatEntries, loads, subproductLoads, batches: allBatches, loadingBatches } = useData();
  const activeBatches = allBatches.filter(b => b.status === 'OPEN');
  const [selectedBatchId, setSelectedBatchId] = useState<string>('');
  const [activeBatch, setActiveBatch] = useState<Batch | null>(null);
  const [toast, setToast] = useState<{ message: string; type: ToastType; visible: boolean }>({
    message: '',
    type: 'info',
    visible: false
  });

  useEffect(() => {
    if (activeBatches.length > 0 && !selectedBatchId) {
      setSelectedBatchId(activeBatches[0].id);
    }
  }, [activeBatches, selectedBatchId]);

  useEffect(() => {
    if (selectedBatchId) {
      const batch = activeBatches.find(b => b.id === selectedBatchId);
      if (batch) {
        setActiveBatch(batch);
      } else if (activeBatches.length > 0) {
        setSelectedBatchId(activeBatches[0].id);
      } else {
        setActiveBatch(null);
      }
    } else if (activeBatches.length > 0) {
      setSelectedBatchId(activeBatches[0].id);
    }
  }, [selectedBatchId, activeBatches]);

  const showToast = (message: string, type: ToastType = 'info') => {
    setToast({ message, type, visible: true });
  };

  // Calculations - STRICTLY FOR ACTIVE BATCH
  const batchWheatEntries = activeBatch 
    ? wheatEntries.filter(e => e.batchId === activeBatch.id)
    : [];
  
  const totalWheat = batchWheatEntries.reduce((acc, curr) => acc + curr.finalWeight, 0);
  
  const batchFlourLoads = activeBatch
    ? loads.filter(l => l.batchId === activeBatch.id)
    : [];

  const totalFlour = batchFlourLoads.reduce((acc, curr) => acc + (curr.weight || 0), 0);

  // Bag counts for active batch
  // To prevent double-counting or contamination from leftover warehouse stocks from previous batches,
  // we count the exact bags associated with this active batch's loads.
  const commonBags = batchFlourLoads.filter(l => l.type === 'C').reduce((acc, curr) => acc + (curr.currentQty || 0), 0);
  const specialBags = batchFlourLoads.filter(l => l.type === 'E').reduce((acc, curr) => acc + (curr.currentQty || 0), 0);
  const wholeBags = batchFlourLoads.filter(l => l.type === 'I').reduce((acc, curr) => acc + (curr.currentQty || 0), 0);
  const glueBags = batchFlourLoads.filter(l => l.type === 'CL').reduce((acc, curr) => acc + (curr.currentQty || 0), 0);

  const batchSubproductLoads = activeBatch
    ? subproductLoads.filter(l => l.batchId === activeBatch.id && l.status === 'FINALIZADO')
    : [];

  const totalBran = batchSubproductLoads.filter(l => l.type === 'FARELO').reduce((acc, curr) => acc + curr.quantity, 0);
  const totalResidue = batchSubproductLoads.filter(l => l.type === 'RESIDUO').reduce((acc, curr) => acc + curr.quantity, 0);
  const totalOtherSub = batchSubproductLoads.filter(l => l.type === 'OUTRO').reduce((acc, curr) => acc + curr.quantity, 0);
  const totalSubproducts = totalBran + totalResidue + totalOtherSub;

  const totalCommonFlourKg = batchFlourLoads
    .filter(l => l.type === 'C')
    .reduce((acc, l) => acc + ((l.weight && l.weight > 0) ? l.weight : (l.currentQty || 0) * 1200), 0);
  const totalSpecialFlourKg = batchFlourLoads
    .filter(l => l.type === 'E')
    .reduce((acc, l) => acc + ((l.weight && l.weight > 0) ? l.weight : (l.currentQty || 0) * 1200), 0);
  const totalWholeFlourKg = batchFlourLoads
    .filter(l => l.type === 'I')
    .reduce((acc, l) => acc + ((l.weight && l.weight > 0) ? l.weight : (l.currentQty || 0) * 1200), 0);
  const totalGlueFlourKg = batchFlourLoads
    .filter(l => l.type === 'CL')
    .reduce((acc, l) => acc + ((l.weight && l.weight > 0) ? l.weight : (l.currentQty || 0) * 1050), 0);

  const totalAmortizedWeight = batchFlourLoads.reduce((acc, l) => acc + (l.isAmortized ? (l.amortizedWeight || 0) : 0), 0);

  const estimatedTotalFlour = totalCommonFlourKg + totalSpecialFlourKg + totalWholeFlourKg + totalGlueFlourKg;
  
  // Flour strictly produced from wheat (removing amortized payload which is just added weight)
  const flourProducedFromWheat = Math.max(0, estimatedTotalFlour - totalAmortizedWeight);
  
  // Calculate the actual bran generated by this batch's flour production to avoid contamination from previous historical silo stock
  // Amortized loads do NOT generate bran.
  const getBranPerBag = (type: string) => type === 'CL' ? 314 : 358;
  const totalBranProducedInBatch = batchFlourLoads.reduce((acc, l) => {
    if (l.isAmortized) return acc; // No bran for returned flour
    return acc + ((l.currentQty || 0) * getBranPerBag(l.type));
  }, 0);
  const estimatedTotalBran = totalBran > 0 ? totalBran : totalBranProducedInBatch;

  const estimatedTotalOutput = estimatedTotalFlour + estimatedTotalBran + totalResidue + totalOtherSub;
  // Use flourProducedFromWheat for mass balance, since amortized flour didn't come from the incoming wheat
  const strictlyProducedOutput = flourProducedFromWheat + estimatedTotalBran + totalResidue + totalOtherSub;
  const massBalance = totalWheat - strictlyProducedOutput;
  const massBalancePercent = totalWheat > 0 ? (massBalance / totalWheat) * 100 : 0;
  
  const extractionRate = totalWheat > 0 ? (flourProducedFromWheat / totalWheat) * 100 : 0;

  // Expected vs Real (based on processed wheat)
  const expectedFlour = totalWheat * 0.77;
  const expectedSubproducts = totalWheat * 0.23;
  const flourDiff = flourProducedFromWheat - expectedFlour;
  const subDiff = (estimatedTotalBran + totalResidue + totalOtherSub) - expectedSubproducts;

  // Predictions & Logistics
  const avgLoadWeight = 17250; // 17.25 tons average as requested by user
  const missingWheatKg = activeBatch ? Math.max(0, activeBatch.targetWheat - totalWheat) : 0;
  const missingFlourKg = activeBatch ? Math.max(0, activeBatch.targetFlour - estimatedTotalFlour) : 0;
  const loadsArrived = batchWheatEntries.length;
  // User requested estimation based on 17250kg average for missing loads
  const loadsMissing = Math.ceil(missingWheatKg / avgLoadWeight);
  const loadsNeededTotal = loadsArrived + loadsMissing;

  // Time Estimation: Capacity from active batch
  const capacity = activeBatch?.millingCapacity || 2500;
  // We calculate based on wheat that still needs to be milled to reach the target flour
  const remainingWheatToMill = activeBatch ? Math.max(0, activeBatch.targetWheat - (estimatedTotalFlour / 0.77)) : 0;
  const hoursRemaining = remainingWheatToMill / capacity;
  const daysRemaining = hoursRemaining / 24;

  // Industrial Loss Limit (1%)
  const isLossAcceptable = massBalancePercent <= 1 && massBalancePercent >= -1;

  return (
    <div className="w-full px-4 pb-12 animate-fadeIn font-inter flex flex-col h-full bg-slate-50 min-h-screen">
      {/* Header */}
      <div className="flex items-center justify-between mb-8 pt-4 sticky top-0 bg-slate-50 z-10 pb-2">
        <div className="flex items-center">
          <button onClick={onBack} className="p-2.5 mr-3 bg-white rounded-xl border border-slate-200 shadow-sm active:scale-95 transition-all text-slate-500">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
          </button>
          <div>
            <h2 className="text-lg font-black text-slate-800 tracking-tight uppercase leading-none">Painel de Controle Industrial</h2>
            <p className="text-[8px] text-slate-400 font-black uppercase tracking-widest mt-1">Balanço Exclusivo do Lote em Vigor</p>
          </div>
        </div>
        
        <div className="flex items-center gap-2 bg-white px-4 py-2 rounded-2xl border border-slate-200 shadow-sm">
          <RefreshCw size={14} className="text-blue-600" />
          <span className="text-[10px] font-black text-slate-600 uppercase tracking-widest">Tempo Real</span>
        </div>
      </div>

      {/* Seleção de Lote Ativo */}
      {loadingBatches ? (
        <div className="mb-6 flex items-center gap-3 bg-blue-50/50 p-3 rounded-2xl border border-blue-100/50">
          <RefreshCw size={12} className="text-blue-600 animate-spin" />
          <span className="text-[9px] font-black text-blue-600 uppercase tracking-widest">Carregando lotes...</span>
        </div>
      ) : activeBatches.length > 1 && (
        <div className="mb-6 flex items-center gap-3 overflow-x-auto pb-2 scrollbar-none">
          <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest whitespace-nowrap">Visualizar Lote:</span>
          {activeBatches.map(batch => (
            <button
              key={batch.id}
              onClick={() => setSelectedBatchId(batch.id)}
              className={`px-4 py-2 rounded-xl font-black text-[10px] uppercase tracking-widest transition-all whitespace-nowrap border-2 ${
                selectedBatchId === batch.id 
                  ? 'bg-blue-600 border-blue-600 text-white shadow-lg shadow-blue-100' 
                  : 'bg-white border-slate-100 text-slate-400 hover:border-blue-200'
              }`}
            >
              {batch.name}
            </button>
          ))}
        </div>
      )}

      {!activeBatch ? (
        <div className="flex-grow flex flex-col items-center justify-center p-12 text-center">
          <div className="w-20 h-20 bg-slate-100 rounded-full flex items-center justify-center text-slate-300 mb-4">
            <AlertCircle size={40} />
          </div>
          <h3 className="text-xl font-black text-slate-800 uppercase tracking-tight">Nenhum Lote Ativo</h3>
          <p className="text-slate-400 text-sm font-medium mt-2">Inicie um novo lote no Sistema de Pedido para ver as análises.</p>
        </div>
      ) : (
        <>
          {/* Active Batch Overview - Compact */}
          <div className="mb-4 bg-slate-900 rounded-2xl p-4 text-white shadow-2xl relative overflow-hidden flex flex-col md:flex-row items-center gap-4">
            <div className="flex items-center gap-3 min-w-[150px]">
              <div className="w-10 h-10 bg-blue-600 rounded-lg flex items-center justify-center shadow-lg shadow-blue-900/20">
                <BarChart3 size={20} />
              </div>
              <div>
                <span className="text-[8px] font-black text-blue-400 uppercase tracking-[0.2em] leading-none">Lote em Vigor</span>
                <h3 className="text-xl font-black uppercase tracking-tighter leading-none mt-0.5">{activeBatch.name}</h3>
              </div>
            </div>

            <div className="flex gap-4 flex-1 justify-around">
              <div className="text-center">
                <span className="text-[7px] font-black text-slate-500 uppercase tracking-widest block leading-none mb-1">Total Trigo</span>
                <span className="text-base font-black tabular-nums">{activeBatch.targetWheat.toLocaleString('pt-BR')} <span className="text-[8px] text-slate-500">kg</span></span>
              </div>
              <div className="text-center">
                <span className="text-[7px] font-black text-slate-500 uppercase tracking-widest block leading-none mb-1">Meta Farinha</span>
                <span className="text-base font-black text-blue-400 tabular-nums">{activeBatch.targetFlour.toLocaleString('pt-BR')} <span className="text-[8px] text-blue-400/50">kg</span></span>
              </div>
              
              <div className="hidden lg:flex flex-col flex-1 max-w-[200px] justify-center">
                <div className="flex justify-between text-[7px] font-black uppercase tracking-widest mb-1">
                  <span className="text-slate-400">Progresso</span>
                  <span className="text-white">{Math.round((estimatedTotalFlour / activeBatch.targetFlour) * 100)}%</span>
                </div>
                <div className="h-1.5 bg-white/5 rounded-full overflow-hidden border border-white/5">
                  <div 
                    className="h-full bg-blue-500 shadow-[0_0_8px_rgba(59,130,246,0.3)] transition-all duration-1000" 
                    style={{ width: `${Math.min(100, (estimatedTotalFlour / activeBatch.targetFlour) * 100)}%` }}
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Logistics & Predictions */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
            {/* Time Estimation Card */}
            <div className="bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-sm flex flex-col">
              <h3 className="text-xs font-black text-slate-400 uppercase tracking-[0.2em] mb-6 flex items-center gap-2">
                <Clock size={16} className="text-blue-600" /> Tempo de Processamento
              </h3>
              
              <div className="space-y-3">
                {[24, 21, 12].map((hPerDay) => {
                  const totalH = remainingWheatToMill / capacity;
                  const totalD = totalH / hPerDay;
                  const d = Math.floor(totalD);
                  const h = Math.round((totalD - d) * hPerDay);
                  
                  return (
                    <div key={hPerDay} className={`p-4 rounded-2xl border flex items-center justify-between ${hPerDay === 24 ? 'bg-blue-50 border-blue-100' : 'bg-slate-50 border-slate-100'}`}>
                      <div className="flex items-center gap-3">
                        <Clock size={14} className={hPerDay === 24 ? 'text-blue-600' : 'text-slate-400'} />
                        <span className="text-[9px] font-bold text-slate-600 uppercase tracking-tight">{hPerDay}h/dia</span>
                      </div>
                      <span className={`text-sm font-black ${hPerDay === 24 ? 'text-blue-700' : 'text-slate-700'}`}>
                        {d > 0 ? `${d}D E ${h}H` : `${h}H`}
                      </span>
                    </div>
                  );
                })}
              </div>
              
              <div className="mt-4 pt-4 border-t border-slate-100 flex justify-between items-center">
                <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Base do Lote:</span>
                <span className="text-xs font-black text-blue-600">{capacity.toLocaleString('pt-BR')} KG/H</span>
              </div>
            </div>

            {/* Wheat Logistics */}
            <div className="bg-white p-8 rounded-[2.5rem] border border-slate-200 shadow-sm">
              <h3 className="text-xs font-black text-slate-400 uppercase tracking-[0.2em] mb-6 flex items-center gap-2">
                <Wheat size={16} className="text-amber-500" /> Logística de Trigo
              </h3>
              <div className="grid grid-cols-2 gap-6">
                <div className="bg-slate-50 p-5 rounded-3xl border border-slate-100">
                  <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-1">Cargas Recebidas</span>
                  <span className="text-3xl font-black text-slate-800">{loadsArrived}</span>
                  <span className="text-[10px] font-bold text-slate-400 block mt-1">CAMINHÕES</span>
                </div>
                <div className="bg-amber-50 p-5 rounded-3xl border border-amber-100">
                  <span className="text-[9px] font-black text-amber-600 uppercase tracking-widest block mb-1">Cargas Faltantes</span>
                  <span className="text-3xl font-black text-amber-700">{loadsMissing}</span>
                  <span className="text-[10px] font-bold text-amber-600 block mt-1">ESTIMATIVA</span>
                </div>
              </div>
              <div className="mt-6 pt-6 border-t border-slate-100">
                <div className="flex justify-between items-center">
                  <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Faltam para fechar pedido:</span>
                  <span className="text-lg font-black text-amber-600">{missingWheatKg.toLocaleString('pt-BR')} kg</span>
                </div>
              </div>
            </div>
          </div>

          {/* Industrial Balance Section */}
          <div className="bg-slate-900 rounded-none p-10 text-white shadow-2xl relative overflow-hidden mb-8 flex flex-col lg:flex-row items-center border border-slate-800">
            <div className="absolute top-0 right-1/2 p-12 opacity-5 pointer-events-none">
              <Scale size={240} />
            </div>
            
            {/* Mass Balance Side */}
            <div className="flex-1 w-full lg:pr-10 lg:border-r border-slate-800 relative z-10">
              <h3 className="text-[10px] font-black text-blue-400 uppercase tracking-[0.3em] mb-10 flex items-center gap-3">
                <BarChart3 size={18} /> Rendimento do Lote (Farinha)
              </h3>

              <div className="grid grid-cols-2 gap-8">
                <div>
                  <span className="text-[8px] font-black text-slate-500 uppercase tracking-widest block mb-2">Entrada Trigo</span>
                  <span className="text-2xl font-black text-white">{totalWheat.toLocaleString('pt-BR')} kg</span>
                </div>
                <div>
                  <span className="text-[8px] font-black text-slate-500 uppercase tracking-widest block mb-2">Total Farinha Estimada</span>
                  <span className="text-2xl font-black text-white">{estimatedTotalFlour.toLocaleString('pt-BR')} kg</span>
                </div>
              </div>
            </div>

            {/* Extraction Rate Side */}
            <div className="w-full lg:w-96 lg:pl-10 mt-10 lg:mt-0 flex flex-col items-center justify-center relative z-10">
              <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] mb-2 text-center">
                Extração Possível
              </h3>
              <p className="text-[7px] text-slate-500 uppercase tracking-widest text-center mb-6 max-w-[200px]">
                Inclui cargas expedidas e farinha não expedida
              </p>
              <div className="relative w-40 h-40 flex items-center justify-center">
                <svg className="w-full h-full transform -rotate-90 drop-shadow-xl">
                  <circle cx="80" cy="80" r="72" stroke="currentColor" strokeWidth="10" fill="transparent" className="text-slate-800" />
                  <circle
                    cx="80"
                    cy="80"
                    r="72"
                    stroke="currentColor"
                    strokeWidth="10"
                    fill="transparent"
                    strokeDasharray={452.39}
                    strokeDashoffset={452.39 - (452.39 * extractionRate) / 100}
                    className="text-blue-500 transition-all duration-1000 ease-out"
                    strokeLinecap="round"
                  />
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <span className="text-4xl font-black text-white tracking-tighter leading-none">{extractionRate.toFixed(1)}</span>
                  <span className="text-[10px] font-black text-blue-500 uppercase tracking-widest mt-1">%</span>
                </div>
              </div>
              <p className="text-[9px] font-bold text-slate-500 uppercase tracking-widest mt-6 text-center">
                Rendimento sobre o Trigo
              </p>
            </div>
          </div>

          {/* Detailed Yield Breakdown */}
          <div className="bg-white rounded-[2rem] border border-slate-200 shadow-sm overflow-hidden mb-4 overflow-x-auto">
            <div className="flex md:grid md:grid-cols-5 divide-x divide-slate-100 min-w-max md:min-w-0">
              
              {/* Comum */}
              <div className="p-6 md:p-8 flex flex-col items-center relative overflow-hidden group min-w-[200px] md:min-w-0">
                <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-50 rounded-full blur-3xl -mr-10 -mt-10 opacity-50 group-hover:opacity-100 transition-opacity"></div>
                
                <h4 className="text-[10px] font-black text-emerald-600 uppercase tracking-[0.2em] mb-6 text-center h-8">
                  Farinha<br/>Comum
                </h4>
                
                <div className="w-20 h-20 md:w-24 md:h-24 mb-6 relative">
                  <img src="https://i.ibb.co/r2PbxJbz/image.png" alt="Comum" className="w-full h-full object-contain drop-shadow-xl" style={{ imageRendering: '-webkit-optimize-contrast' }} referrerPolicy="no-referrer" />
                </div>
                
                <div className="flex flex-col items-center space-y-4 w-full relative z-10">
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-base md:text-lg font-black text-slate-800 leading-none block">{commonBags.toLocaleString('pt-BR')} <span className="text-[10px] md:text-xs text-slate-500 font-bold uppercase">bags</span></span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-base md:text-lg font-black text-slate-800 leading-none block">{totalCommonFlourKg.toLocaleString('pt-BR')} <span className="text-[10px] md:text-xs text-slate-500 font-bold uppercase">kg</span></span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-xs md:text-sm font-black text-slate-700 leading-none block">
                      {estimatedTotalFlour > 0 ? ((totalCommonFlourKg / estimatedTotalFlour) * 100).toFixed(2) : '0.00'}%
                    </span>
                    <span className="text-[7px] md:text-[8px] font-bold text-slate-400 uppercase tracking-widest mt-1 block">da Farinha</span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-xs md:text-sm font-black text-slate-700 leading-none block">
                      {totalWheat > 0 ? ((totalCommonFlourKg / totalWheat) * 100).toFixed(2) : '0.00'}%
                    </span>
                    <span className="text-[7px] md:text-[8px] font-bold text-slate-400 uppercase tracking-widest mt-1 block">do Trigo</span>
                  </div>

                  <div className="text-center w-full pt-2">
                    <span className="text-2xl md:text-3xl font-black text-emerald-600 tracking-tighter">
                      {estimatedTotalFlour > 0 ? ((totalCommonFlourKg / estimatedTotalFlour) * 100).toFixed(2) : '0.00'}%
                    </span>
                  </div>
                </div>
              </div>

              {/* Especial */}
              <div className="p-6 md:p-8 flex flex-col items-center relative overflow-hidden group min-w-[200px] md:min-w-0">
                <div className="absolute top-0 right-0 w-32 h-32 bg-blue-50 rounded-full blur-3xl -mr-10 -mt-10 opacity-50 group-hover:opacity-100 transition-opacity"></div>
                
                <h4 className="text-[10px] font-black text-blue-600 uppercase tracking-[0.2em] mb-6 text-center h-8">
                  Farinha<br/>Especial
                </h4>
                
                <div className="w-20 h-20 md:w-24 md:h-24 mb-6 relative">
                  <img src="https://i.ibb.co/3yYgYdjn/image.png" alt="Especial" className="w-full h-full object-contain drop-shadow-xl" style={{ imageRendering: '-webkit-optimize-contrast' }} referrerPolicy="no-referrer" />
                </div>
                
                <div className="flex flex-col items-center space-y-4 w-full relative z-10">
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-base md:text-lg font-black text-slate-800 leading-none block">{specialBags.toLocaleString('pt-BR')} <span className="text-[10px] md:text-xs text-slate-500 font-bold uppercase">bags</span></span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-base md:text-lg font-black text-slate-800 leading-none block">{totalSpecialFlourKg.toLocaleString('pt-BR')} <span className="text-[10px] md:text-xs text-slate-500 font-bold uppercase">kg</span></span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-xs md:text-sm font-black text-slate-700 leading-none block">
                      {estimatedTotalFlour > 0 ? ((totalSpecialFlourKg / estimatedTotalFlour) * 100).toFixed(2) : '0.00'}%
                    </span>
                    <span className="text-[7px] md:text-[8px] font-bold text-slate-400 uppercase tracking-widest mt-1 block">da Farinha</span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-xs md:text-sm font-black text-slate-700 leading-none block">
                      {totalWheat > 0 ? ((totalSpecialFlourKg / totalWheat) * 100).toFixed(2) : '0.00'}%
                    </span>
                    <span className="text-[7px] md:text-[8px] font-bold text-slate-400 uppercase tracking-widest mt-1 block">do Trigo</span>
                  </div>

                  <div className="text-center w-full pt-2">
                    <span className="text-2xl md:text-3xl font-black text-blue-600 tracking-tighter">
                      {estimatedTotalFlour > 0 ? ((totalSpecialFlourKg / estimatedTotalFlour) * 100).toFixed(2) : '0.00'}%
                    </span>
                  </div>
                </div>
              </div>

              {/* Inteira */}
              <div className="p-6 md:p-8 flex flex-col items-center relative overflow-hidden group min-w-[200px] md:min-w-0">
                <div className="absolute top-0 right-0 w-32 h-32 bg-red-50 rounded-full blur-3xl -mr-10 -mt-10 opacity-50 group-hover:opacity-100 transition-opacity"></div>
                
                <h4 className="text-[10px] font-black text-red-600 uppercase tracking-[0.2em] mb-6 text-center h-8">
                  Farinha<br/>Inteira
                </h4>
                
                <div className="w-20 h-20 md:w-24 md:h-24 mb-6 relative">
                  <img src="https://i.ibb.co/Xn0XLJM/image.png" alt="Inteira" className="w-full h-full object-contain drop-shadow-xl" style={{ imageRendering: '-webkit-optimize-contrast' }} referrerPolicy="no-referrer" />
                </div>
                
                <div className="flex flex-col items-center space-y-4 w-full relative z-10">
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-base md:text-lg font-black text-slate-800 leading-none block">{wholeBags.toLocaleString('pt-BR')} <span className="text-[10px] md:text-xs text-slate-500 font-bold uppercase">bags</span></span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-base md:text-lg font-black text-slate-800 leading-none block">{totalWholeFlourKg.toLocaleString('pt-BR')} <span className="text-[10px] md:text-xs text-slate-500 font-bold uppercase">kg</span></span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-xs md:text-sm font-black text-slate-700 leading-none block">
                      {estimatedTotalFlour > 0 ? ((totalWholeFlourKg / estimatedTotalFlour) * 100).toFixed(2) : '0.00'}%
                    </span>
                    <span className="text-[7px] md:text-[8px] font-bold text-slate-400 uppercase tracking-widest mt-1 block">da Farinha</span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-xs md:text-sm font-black text-slate-700 leading-none block">
                      {totalWheat > 0 ? ((totalWholeFlourKg / totalWheat) * 100).toFixed(2) : '0.00'}%
                    </span>
                    <span className="text-[7px] md:text-[8px] font-bold text-slate-400 uppercase tracking-widest mt-1 block">do Trigo</span>
                  </div>

                  <div className="text-center w-full pt-2">
                    <span className="text-2xl md:text-3xl font-black text-red-600 tracking-tighter">
                      {estimatedTotalFlour > 0 ? ((totalWholeFlourKg / estimatedTotalFlour) * 100).toFixed(2) : '0.00'}%
                    </span>
                  </div>
                </div>
              </div>

              {/* Cola */}
              <div className="p-6 md:p-8 flex flex-col items-center relative overflow-hidden group min-w-[200px] md:min-w-0">
                <div className="absolute top-0 right-0 w-32 h-32 bg-slate-100 rounded-full blur-3xl -mr-10 -mt-10 opacity-50 group-hover:opacity-100 transition-opacity"></div>
                
                <h4 className="text-[10px] font-black text-slate-800 uppercase tracking-[0.2em] mb-6 text-center h-8">
                  Farinha<br/>Cola
                </h4>
                
                <div className="w-20 h-20 md:w-24 md:h-24 mb-6 relative">
                  <img src="https://i.ibb.co/8LDzkhh8/image.png" alt="Cola" className="w-full h-full object-contain drop-shadow-xl" style={{ imageRendering: '-webkit-optimize-contrast' }} referrerPolicy="no-referrer" />
                </div>
                
                <div className="flex flex-col items-center space-y-4 w-full relative z-10">
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-base md:text-lg font-black text-slate-800 leading-none block">{glueBags.toLocaleString('pt-BR')} <span className="text-[10px] md:text-xs text-slate-500 font-bold uppercase">bags</span></span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-base md:text-lg font-black text-slate-800 leading-none block">{totalGlueFlourKg.toLocaleString('pt-BR')} <span className="text-[10px] md:text-xs text-slate-500 font-bold uppercase">kg</span></span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-xs md:text-sm font-black text-slate-700 leading-none block">
                      {estimatedTotalFlour > 0 ? ((totalGlueFlourKg / estimatedTotalFlour) * 100).toFixed(2) : '0.00'}%
                    </span>
                    <span className="text-[7px] md:text-[8px] font-bold text-slate-400 uppercase tracking-widest mt-1 block">da Farinha</span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-slate-50">
                    <span className="text-xs md:text-sm font-black text-slate-700 leading-none block">
                      {totalWheat > 0 ? ((totalGlueFlourKg / totalWheat) * 100).toFixed(2) : '0.00'}%
                    </span>
                    <span className="text-[7px] md:text-[8px] font-bold text-slate-400 uppercase tracking-widest mt-1 block">do Trigo</span>
                  </div>

                  <div className="text-center w-full pt-2">
                    <span className="text-2xl md:text-3xl font-black text-slate-800 tracking-tighter">
                      {estimatedTotalFlour > 0 ? ((totalGlueFlourKg / estimatedTotalFlour) * 100).toFixed(2) : '0.00'}%
                    </span>
                  </div>
                </div>
              </div>

              {/* Farelo */}
              <div className="p-6 md:p-8 flex flex-col items-center relative overflow-hidden group bg-orange-50/10 min-w-[200px] md:min-w-0">
                <div className="absolute top-0 right-0 w-32 h-32 bg-orange-100 rounded-full blur-3xl -mr-10 -mt-10 opacity-50 group-hover:opacity-100 transition-opacity"></div>
                
                <h4 className="text-[10px] font-black text-orange-800 uppercase tracking-[0.2em] mb-6 text-center h-8">
                  Farelo<br/>(Subproduto)
                </h4>
                
                <div className="w-20 h-20 md:w-24 md:h-24 mb-6 relative">
                  <img src="https://i.ibb.co/chcGNGq8/image.png" alt="Farelo" className="w-full h-full object-contain drop-shadow-xl" style={{ imageRendering: '-webkit-optimize-contrast' }} referrerPolicy="no-referrer" />
                </div>
                
                <div className="flex flex-col items-center space-y-4 w-full relative z-10">
                  <div className="text-center w-full pb-3 border-b border-orange-50">
                    <span className="text-base md:text-lg font-black text-slate-400 leading-none block italic">N/A</span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-orange-50">
                    <span className="text-base md:text-lg font-black text-slate-800 leading-none block">{estimatedTotalBran.toLocaleString('pt-BR')} <span className="text-[10px] md:text-xs text-slate-500 font-bold uppercase">kg</span></span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-orange-50">
                    <span className="text-xs md:text-sm font-black text-slate-700 leading-none block">
                      {estimatedTotalOutput > 0 ? ((estimatedTotalBran / estimatedTotalOutput) * 100).toFixed(2) : '0.00'}%
                    </span>
                    <span className="text-[7px] md:text-[8px] font-bold text-slate-400 uppercase tracking-widest mt-1 block">da produção</span>
                  </div>
                  
                  <div className="text-center w-full pb-3 border-b border-orange-50">
                    <span className="text-xs md:text-sm font-black text-slate-700 leading-none block">
                      {totalWheat > 0 ? ((estimatedTotalBran / totalWheat) * 100).toFixed(2) : '0.00'}%
                    </span>
                    <span className="text-[7px] md:text-[8px] font-bold text-slate-400 uppercase tracking-widest mt-1 block">do Trigo</span>
                  </div>

                  <div className="text-center w-full pt-2">
                    <span className="text-2xl md:text-3xl font-black text-orange-800 tracking-tighter">
                      {totalWheat > 0 ? ((estimatedTotalBran / totalWheat) * 100).toFixed(2) : '0.00'}%
                    </span>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </>
      )}

      <Toast 
        isVisible={toast.visible} 
        message={toast.message} 
        type={toast.type} 
        onClose={() => setToast(prev => ({ ...prev, visible: false }))} 
      />
    </div>
  );
};
