
import React, { useState, useMemo } from 'react';
import { 
  Package, 
  ClipboardCheck, 
  Droplets, 
  TrendingUp, 
  Truck, 
  ChevronLeft,
  LayoutGrid,
  Save,
  CheckCircle2,
  Clock,
  Microscope,
  Palette,
  Zap,
  Scale,
  AlertTriangle,
  History,
  Activity,
  Calendar,
  Share2,
  Send,
  Image
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import html2canvas from 'html2canvas-pro';
import { 
  PieChart, 
  Pie, 
  Cell, 
  ResponsiveContainer, 
  Tooltip as RechartsTooltip 
} from 'recharts';
import { useData } from '../../shared/contexts/DataContext';
import { Logo } from '../../../components/Logo';
import { saveAnalysis, saveExtraction } from '../../../firebase';

type MobileTab = 'dashboard' | 'analyses' | 'extraction' | 'wheat' | 'validity';

const STANDARD_BAG_WEIGHT = 1200;
const COLA_BAG_WEIGHT = 1050;
const TOTAL_CAPACITY = 120;

export const AppMobile: React.FC = () => {
  const [activeTab, setActiveTab] = useState<MobileTab>('dashboard');
  const { stock, wheatEntries, analyses, history, batches, loads = [], subproductLoads = [] } = useData();
  const [isSaving, setIsSaving] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [showExtractionResults, setShowExtractionResults] = useState(false);
  const [extractionSubTab, setExtractionSubTab] = useState<'realtime' | 'simulator'>('simulator');

  // Get active batch for wheat/bran info
  const activeBatch = useMemo(() => batches.find(b => b.status === 'OPEN'), [batches]);

  // ACTIVE BATCH COMPUTED METRICS (STRICTLY FOR ACTIVE BATCH)
  const activeBatchMetrics = useMemo(() => {
    if (!activeBatch) return null;

    const batchWheatEntries = wheatEntries.filter(e => e.batchId === activeBatch.id);
    const totalWheat = batchWheatEntries.reduce((acc, curr) => acc + (curr.finalWeight || 0), 0);

    const batchFlourLoads = loads.filter(l => l.batchId === activeBatch.id);
    
    // Bag counts for active batch
    // To prevent double-counting or contamination from leftover warehouse stocks from previous batches,
    // we count the exact bags associated with this active batch's loads.
    const commonBags = batchFlourLoads.filter(l => l.type === 'C').reduce((acc, curr) => acc + (curr.currentQty || 0), 0);
    const specialBags = batchFlourLoads.filter(l => l.type === 'E').reduce((acc, curr) => acc + (curr.currentQty || 0), 0);
    const wholeBags = batchFlourLoads.filter(l => l.type === 'I').reduce((acc, curr) => acc + (curr.currentQty || 0), 0);
    const glueBags = batchFlourLoads.filter(l => l.type === 'CL').reduce((acc, curr) => acc + (curr.currentQty || 0), 0);

    const batchSubproductLoads = subproductLoads.filter(l => l.batchId === activeBatch.id && l.status === 'FINALIZADO');

    const totalBran = batchSubproductLoads.filter(l => l.type === 'FARELO').reduce((acc, curr) => acc + (curr.quantity || 0), 0);
    const totalResidue = batchSubproductLoads.filter(l => l.type === 'RESIDUO').reduce((acc, curr) => acc + (curr.quantity || 0), 0);
    const totalOtherSub = batchSubproductLoads.filter(l => l.type === 'OUTRO').reduce((acc, curr) => acc + (curr.quantity || 0), 0);

    const totalCommonFlourKg = batchFlourLoads
      .filter(l => l.type === 'C')
      .reduce((acc, l) => acc + ((l.weight && l.weight > 0) ? l.weight : (l.currentQty || 0) * 1200), 0);
    const totalSpecialFlourKg = batchFlourLoads
      .filter(l => l.type === 'E')
      .reduce((acc, l) => acc + ((l.weight && l.weight > 0) ? l.weight : (l.currentQty || 0) * 1200), 0);
    const totalWholeFlourKg = batchFlourLoads
      .filter(l => l.type === 'I')
      .reduce((acc, l) => acc + ((l.weight && l.weight > 0) ? l.weight : (l.currentQty || 0) * 1200), 0);
    const totalGlueFlourKg = batchFlourLoads
      .filter(l => l.type === 'CL')
      .reduce((acc, l) => acc + ((l.weight && l.weight > 0) ? l.weight : (l.currentQty || 0) * 1050), 0);

    const totalAmortizedWeight = batchFlourLoads.reduce((acc, l) => acc + (l.isAmortized ? (l.amortizedWeight || 0) : 0), 0);

    const estimatedTotalFlour = totalCommonFlourKg + totalSpecialFlourKg + totalWholeFlourKg + totalGlueFlourKg;
    
    // Flour strictly produced from wheat (removing amortized payload which is just added weight)
    const flourProducedFromWheat = Math.max(0, estimatedTotalFlour - totalAmortizedWeight);
    
    // Calculate the actual bran generated by this batch's flour production to avoid contamination from previous historical silo stock
    // Amortized loads do NOT generate bran.
    const getBranPerBag = (type: string) => type === 'CL' ? 314 : 358;
    const totalBranProducedInBatch = batchFlourLoads.reduce((acc, l) => {
      if (l.isAmortized) return acc; // No bran for returned flour
      return acc + ((l.currentQty || 0) * getBranPerBag(l.type));
    }, 0);
    const estimatedTotalBran = totalBran > 0 ? totalBran : totalBranProducedInBatch;

    const estimatedTotalOutput = estimatedTotalFlour + estimatedTotalBran + totalResidue + totalOtherSub;
    
    // actualExtractionRate (% of strictly produced flour over total processed wheat)
    const actualExtractionRate = totalWheat > 0 ? (flourProducedFromWheat / totalWheat) * 100 : 0;

    // Flour type ratios over processed wheat:
    const specialPctOfWheat = totalWheat > 0 ? (totalSpecialFlourKg / totalWheat) * 100 : 0;
    const commonPctOfWheat = totalWheat > 0 ? (totalCommonFlourKg / totalWheat) * 100 : 0;
    const wholePctOfWheat = totalWheat > 0 ? (totalWholeFlourKg / totalWheat) * 100 : 0;
    const gluePctOfWheat = totalWheat > 0 ? (totalGlueFlourKg / totalWheat) * 100 : 0;

    return {
      totalWheat,
      estimatedTotalFlour,
      commonBags,
      specialBags,
      wholeBags,
      glueBags,
      totalCommonFlourKg,
      totalSpecialFlourKg,
      totalWholeFlourKg,
      totalGlueFlourKg,
      actualExtractionRate,
      specialPctOfWheat,
      commonPctOfWheat,
      wholePctOfWheat,
      gluePctOfWheat,
      totalBran,
      totalResidue,
      totalOtherSub,
      estimatedTotalOutput,
      estimatedTotalBran
    };
  }, [activeBatch, wheatEntries, loads, subproductLoads, stock]);

  const calculateWeight = (bags: number, isGlue: boolean = false) => bags * (isGlue ? COLA_BAG_WEIGHT : STANDARD_BAG_WEIGHT);
  const formatWeight = (weight: number) => weight.toLocaleString('pt-BR');

  const totalBags = stock.common + stock.special + stock.whole + stock.glue;
  const occupancyPercent = Math.min(Math.round((totalBags / TOTAL_CAPACITY) * 100), 100);
  const totalWeightStock = 
    calculateWeight(stock.common) + 
    calculateWeight(stock.special) + 
    calculateWeight(stock.whole) + 
    calculateWeight(stock.glue, true);

  // Analysis Form State
  const [analysisForm, setAnalysisForm] = useState({
    type: 'ESPECIAL',
    color: '',
    humidity: ''
  });

  // Extraction Form State
  const [extractionForm, setExtractionForm] = useState({
    special: '',
    common: '',
    whole: '',
    glue: '',
    bran: ''
  });

  // Validity Calculator State
  const [validityType, setValidityType] = useState<'farinha' | 'farelo'>('farinha');
  const [prodDate, setProdDate] = useState<string>(() => {
    const today = new Date();
    const yyyy = today.getFullYear();
    const mm = String(today.getMonth() + 1).padStart(2, '0');
    const dd = String(today.getDate()).padStart(2, '0');
    return `${yyyy}-${mm}-${dd}`;
  });

  // State for load alerts and sound notification
  const [knownWheatIds, setKnownWheatIds] = useState<Set<string> | null>(null);
  const [alertsEnabled, setAlertsEnabled] = useState<boolean>(() => {
    return localStorage.getItem('mocca_wheat_alerts_enabled') !== 'false';
  });

  // Sharing states
  const [isSharing, setIsSharing] = useState<boolean>(false);

  // Loud and premium digital warning chime synthesizer using Web Audio API
  const playWheatAlertSound = () => {
    try {
      const AudioCtx = window.AudioContext || (window as any).webkitAudioContext;
      if (!AudioCtx) return;
      const ctx = new AudioCtx();
      const now = ctx.currentTime;

      const playTone = (time: number, freq: number, duration: number, volume: number) => {
        const osc = ctx.createOscillator();
        const sub = ctx.createOscillator();
        const gain = ctx.createGain();

        osc.type = 'sine';
        osc.frequency.setValueAtTime(freq, time);
        // Subtle descend sweep to resemble heavy warning/arrival alert
        osc.frequency.exponentialRampToValueAtTime(freq * 0.9, time + duration);

        sub.type = 'triangle';
        sub.frequency.setValueAtTime(freq / 2, time);
        sub.frequency.exponentialRampToValueAtTime(freq * 0.45, time + duration);

        gain.gain.setValueAtTime(volume, time);
        gain.gain.exponentialRampToValueAtTime(0.001, time + duration);

        osc.connect(gain);
        sub.connect(gain);
        gain.connect(ctx.destination);

        osc.start(time);
        sub.start(time);
        osc.stop(time + duration);
        sub.stop(time + duration);
      };

      // Sound signature: 2 loud high-alert metallic beeps + heavy drop/alarm sound
      playTone(now, 1600, 0.15, 0.82);
      playTone(now + 0.18, 1600, 0.15, 0.82);
      playTone(now + 0.36, 1200, 0.35, 0.7);
      playTone(now + 0.52, 750, 0.55, 0.6);
    } catch (e) {
      console.warn("Failed to generate synthetic alert audio:", e);
    }
  };

  // Test notification function for checking mobile compatibility
  const testAlert = () => {
    playWheatAlertSound();
    if (typeof window !== 'undefined' && 'Notification' in window) {
      if (Notification.permission === 'default') {
        Notification.requestPermission().then(permission => {
          if (permission === 'granted') {
            new Notification("🌾 MOCCA ERP • SISTEMA ATIVO", {
              body: "Suas notificações e avisos sonoros de trigo foram configurados com sucesso!",
              icon: "https://i.ibb.co/DgbmXFt0/image.png"
            });
          }
        });
      } else if (Notification.permission === 'granted') {
        new Notification("🌾 TESTE DE NOTIFICAÇÃO", {
          body: "Sucesso! O sinal sonoro e as notificações no Android estão prontas.",
          icon: "https://i.ibb.co/DgbmXFt0/image.png"
        });
      }
    }
  };

  // Setup Notification listener for new wheat load entries
  React.useEffect(() => {
    if (wheatEntries && wheatEntries.length > 0) {
      const currentIds = new Set(wheatEntries.map(e => e.id).filter(Boolean) as string[]);
      
      if (knownWheatIds === null) {
        // First application load, populate known IDs so past logs do not trigger alarms on start
        setKnownWheatIds(currentIds);
        return;
      }

      // Check for incoming entries
      const newEntries = wheatEntries.filter(e => e.id && !knownWheatIds.has(e.id));
      if (newEntries.length > 0) {
        setKnownWheatIds(currentIds);

        // Calculate total today
        const now = new Date();
        const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
        const todayLoads = wheatEntries.filter(entry => {
          if (!entry.date) return false;
          const entryDate = entry.date.toDate ? entry.date.toDate().getTime() : new Date(entry.date).getTime();
          return entryDate >= todayStart;
        });
        const todayWeightSum = todayLoads.reduce((sum, load) => sum + (load.finalWeight || 0), 0);

        newEntries.forEach(entry => {
          // Play loud alarm
          playWheatAlertSound();

          // Push native notification to client
          if (typeof window !== 'undefined' && 'Notification' in window && Notification.permission === 'granted') {
            const entryWeightStr = Number(entry.finalWeight || entry.entryWeight || 0).toLocaleString('pt-BR');
            const totalWeightStr = Number(todayWeightSum).toLocaleString('pt-BR');
            
            new Notification("🌾 CHEGOU TRIGO!", {
              body: `Carga: ${entryWeightStr} kg • ${entry.driver || 'Sem Motorista'}\nTotal hoje: ${totalWeightStr} kg no sistema!`,
              icon: "https://i.ibb.co/DgbmXFt0/image.png",
              tag: 'wheat-update-' + entry.id
            });
          }
        });
      }
    } else if (wheatEntries && wheatEntries.length === 0 && knownWheatIds === null) {
      setKnownWheatIds(new Set());
    }
  }, [wheatEntries, knownWheatIds]);

  const extractionResults = useMemo(() => {
    const cleanNumber = (val: string) => (val || '').replace(/\./g, '').replace(',', '.');
    const s = parseFloat(cleanNumber(extractionForm.special)) || 0;
    const c = parseFloat(cleanNumber(extractionForm.common)) || 0;
    const w = parseFloat(cleanNumber(extractionForm.whole)) || 0;
    const g = parseFloat(cleanNumber(extractionForm.glue)) || 0;
    const b = parseFloat(cleanNumber(extractionForm.bran)) || 0;

    const specialH = Math.round(s * 360);
    const commonH = Math.round(c * 360);
    const wholeH = Math.round(w * 360);
    const glueH = Math.round(g * 360);
    const branH = Math.round(b * 360);

    const totalFlour = specialH + commonH + wholeH + glueH;
    const totalProducts = totalFlour + branH;
    
    // Efficiency Metrics based on total output
    const extractionPercent = totalProducts > 0 ? (totalFlour / totalProducts) * 100 : 0;
    const branPercent = totalProducts > 0 ? (branH / totalProducts) * 100 : 0;
    
    // Estimated Wheat Input based on 78% standard (or actual extraction)
    // Formula: Total Flour / (Extraction% / 100)
    const estimatedWheatInput = extractionPercent > 0 ? (totalFlour / (extractionPercent / 100)) : 0;

    return {
      special: specialH,
      common: commonH,
      whole: wholeH,
      glue: glueH,
      bran: branH,
      totalFlour,
      totalProducts,
      extractionPercent,
      branPercent,
      estimatedWheatInput,
      yield: extractionPercent
    };
  }, [extractionForm]);

  const wheatStats = useMemo(() => {
    const now = new Date();
    const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
    const yesterdayStart = todayStart - 24 * 60 * 60 * 1000;

    const todayLoads = wheatEntries.filter(entry => {
      if (!entry.date) return false;
      const entryDate = entry.date.toDate ? entry.date.toDate().getTime() : new Date(entry.date).getTime();
      return entryDate >= todayStart;
    });

    const yesterdayLoads = wheatEntries.filter(entry => {
      if (!entry.date) return false;
      const entryDate = entry.date.toDate ? entry.date.toDate().getTime() : new Date(entry.date).getTime();
      return entryDate >= yesterdayStart && entryDate < todayStart;
    });

    const todayWeight = todayLoads.reduce((sum, load) => sum + (load.finalWeight || 0), 0);
    const yesterdayWeight = yesterdayLoads.reduce((sum, load) => sum + (load.finalWeight || 0), 0);

    // Calculate dynamic average moisture and average ph of today's wheat loads
    const moistureEntries = todayLoads.filter(l => l.moisture !== undefined && l.moisture !== null && !isNaN(Number(l.moisture)) && Number(l.moisture) > 0);
    const avgMoisture = moistureEntries.length > 0
      ? moistureEntries.reduce((sum, l) => sum + Number(l.moisture), 0) / moistureEntries.length
      : 12.5;

    const phEntries = todayLoads.filter(l => l.ph !== undefined && l.ph !== null && !isNaN(Number(l.ph)) && Number(l.ph) > 0);
    const avgPh = phEntries.length > 0
      ? phEntries.reduce((sum, l) => sum + Number(l.ph), 0) / phEntries.length
      : 78;

    return {
      todayLoads,
      yesterdayLoads,
      todayWeight,
      yesterdayWeight,
      avgMoisture,
      avgPh,
      totalWeight: todayWeight + yesterdayWeight
    };
  }, [wheatEntries]);

  const maskBrazilian = (value: string, decimals: number = 2) => {
    const digits = (value || '').replace(/\D/g, '');
    if (!digits) return '';
    const numberValue = Number(digits) / Math.pow(10, decimals);
    return numberValue.toLocaleString('pt-BR', {
      minimumFractionDigits: decimals,
      maximumFractionDigits: decimals
    });
  };

  const maskHumidity = (value: string) => {
    const digits = (value || '').replace(/\D/g, '').slice(0, 3);
    if (!digits) return '';
    if (digits.length <= 2) return digits;
    return digits.slice(0, 2) + ',' + digits.slice(2);
  };

  const handleSaveAnalysis = async () => {
    if (!analysisForm.color || !analysisForm.humidity) return;
    setIsSaving(true);
    const cleanNumber = (val: string) => (val || '').replace(/\./g, '').replace(',', '.');
    const success = await saveAnalysis({
      type: analysisForm.type,
      color: parseFloat(cleanNumber(analysisForm.color)) || 0,
      moisture: parseFloat(cleanNumber(analysisForm.humidity)) || 0
    });
    if (success) {
      setAnalysisForm({ ...analysisForm, color: '', humidity: '' });
      setShowSuccess(true);
      setTimeout(() => setShowSuccess(false), 3000);
      setActiveTab('dashboard');
    }
    setIsSaving(false);
  };

  const handleSaveExtraction = async () => {
    setIsSaving(true);
    try {
      const success = await saveExtraction({
        flourTotal: extractionResults.totalFlour,
        bran: extractionResults.bran,
        yieldPercentage: extractionResults.yield,
        breakdown: {
          special: extractionResults.special,
          common: extractionResults.common,
          whole: extractionResults.whole,
          glue: extractionResults.glue
        }
      });
      if (success) {
        setExtractionForm({ special: '', common: '', whole: '', glue: '', bran: '' });
        setShowExtractionResults(false);
        setShowSuccess(true);
        setTimeout(() => setShowSuccess(false), 3000);
      }
    } catch (error) {
      console.error("Error saving extraction:", error);
    } finally {
      setIsSaving(false);
    }
  };


  const renderTabContent = () => {
    switch (activeTab) {
      case 'dashboard':
        return (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* Logo and Greeting */}
            <div className="flex flex-col items-center mb-4 pt-4">
              <div className="w-full max-w-[280px]">
                <Logo />
              </div>
            </div>

            <div className="flex flex-col">
              {/* Active Batch Header */}
              <motion.div 
                initial={{ scale: 0.95, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ type: "spring", stiffness: 300, damping: 25 }}
                className="-mx-6 bg-gradient-to-br from-slate-900 via-blue-950 to-slate-900 pt-8 pb-8 px-6 text-white relative overflow-hidden shadow-[0_10px_30px_0px_rgba(0,0,0,0.3)] z-20 rounded-b-xl"
              >
                 {/* Animated Background Elements */}
                 <motion.div 
                   animate={{ rotate: 360 }}
                   transition={{ duration: 50, repeat: Infinity, ease: "linear" }}
                   className="absolute -top-20 -right-20 w-64 h-64 bg-blue-500/10 rounded-full blur-3xl pointer-events-none"
                 />
                 <motion.div 
                   animate={{ rotate: -360 }}
                   transition={{ duration: 70, repeat: Infinity, ease: "linear" }}
                   className="absolute -bottom-20 -left-20 w-64 h-64 bg-amber-500/10 rounded-full blur-3xl pointer-events-none"
                 />
                 
                 <motion.div 
                   animate={{ y: [0, -10, 0] }}
                   transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
                   className="absolute top-4 right-4 p-4 opacity-10 drop-shadow-2xl"
                 >
                   <Package size={100} />
                 </motion.div>

                 <div className="relative z-10 text-center mb-6">
                    <div className="inline-block bg-blue-500/20 border border-blue-400/30 backdrop-blur-sm px-4 py-1.5 rounded-full mb-4 shadow-[0_0_15px_rgba(59,130,246,0.5)] animate-pulse shadow-blue-500/20">
                      <span className="text-[10px] font-black text-blue-300 uppercase tracking-[0.3em]">Lote em Vigor</span>
                    </div>
                    <h2 className="text-6xl font-[950] uppercase tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-white via-blue-50 to-white drop-shadow-[0_4px_12px_rgba(59,130,246,0.3)] mb-2 leading-none">{activeBatch?.name || 'NENHUM LOTE'}</h2>
                    {activeBatch && (
                       <p className="text-[11px] text-blue-200/70 font-bold uppercase tracking-widest">
                         Iniciado em {activeBatch.createdAt ? (activeBatch.createdAt.toDate ? activeBatch.createdAt.toDate().toLocaleDateString('pt-BR') : (isNaN(new Date(activeBatch.createdAt).getTime()) ? '---' : new Date(activeBatch.createdAt).toLocaleDateString('pt-BR'))) : '---'}
                       </p>
                    )}
                 </div>

                 {activeBatch && (
                   <div className="space-y-5 relative z-10 pt-4">
                      {/* Trigo Lançado Progress */}
                      <div className="bg-white/5 backdrop-blur-md rounded-2xl p-4 border border-white/10 shadow-inner">
                         <div className="flex justify-between items-end mb-2">
                            <div>
                              <span className="text-[10px] font-black text-amber-400 uppercase tracking-widest block mb-0.5">Trigo Lançado (Meta: {(activeBatch.targetWheat || 0).toLocaleString('pt-BR')} kg)</span>
                              <span className="text-2xl font-black text-white">{(activeBatch.currentWheat || 0).toLocaleString('pt-BR')} <span className="text-[10px] text-slate-400">kg</span></span>
                            </div>
                            <span className="text-xs font-black text-amber-400 bg-amber-400/10 px-2 py-1 rounded-lg">
                              {Math.round(((activeBatch.currentWheat || 0) / (activeBatch.targetWheat || 1)) * 100)}%
                            </span>
                         </div>
                         <div className="w-full bg-slate-800 rounded-full h-2 overflow-hidden border border-white/5">
                            <motion.div 
                              initial={{ width: 0 }}
                              animate={{ width: `${Math.min(100, ((activeBatch.currentWheat || 0) / (activeBatch.targetWheat || 1)) * 100)}%` }}
                              transition={{ duration: 1.5, ease: "easeOut" }}
                              className="bg-gradient-to-r from-amber-500 to-amber-300 h-2 rounded-full shadow-[0_0_10px_rgba(245,158,11,0.5)]" 
                            />
                         </div>
                      </div>

                      {/* Farinha Produzida Progress */}
                      <div className="bg-white/5 backdrop-blur-md rounded-2xl p-4 border border-white/10 shadow-inner">
                         <div className="flex justify-between items-end mb-2">
                            <div>
                              <span className="text-[10px] font-black text-blue-400 uppercase tracking-widest block mb-0.5">Farinha Produzida (Meta: {(activeBatch.targetFlour || 0).toLocaleString('pt-BR')} kg)</span>
                              <span className="text-2xl font-black text-white">{(activeBatch.currentFlour || 0).toLocaleString('pt-BR')} <span className="text-[10px] text-slate-400">kg</span></span>
                            </div>
                            <span className="text-xs font-black text-blue-400 bg-blue-400/10 px-2 py-1 rounded-lg">
                              {Math.round(((activeBatch.currentFlour || 0) / (activeBatch.targetFlour || 1)) * 100)}%
                            </span>
                         </div>
                         <div className="w-full bg-slate-800 rounded-full h-2 overflow-hidden border border-white/5">
                            <motion.div 
                              initial={{ width: 0 }}
                              animate={{ width: `${Math.min(100, ((activeBatch.currentFlour || 0) / (activeBatch.targetFlour || 1)) * 100)}%` }}
                              transition={{ duration: 1.5, ease: "easeOut", delay: 0.2 }}
                              className="bg-gradient-to-r from-blue-500 to-cyan-300 h-2 rounded-full shadow-[0_0_10px_rgba(59,130,246,0.5)]" 
                            />
                         </div>
                      </div>
                   </div>
                 )}
              </motion.div>

              {/* Visual Divider (Filete) */}
              <motion.div
                initial={{ scale: 0.95, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ type: "spring", stiffness: 300, damping: 25, delay: 0.05 }}
                className="-mx-6 h-32 overflow-hidden relative -mt-6 -mb-6 z-10"
              >
                <img 
                  src="wheat_divider_blue.png" 
                  alt="Paisagem Trigo" 
                  className="w-full h-full object-cover object-center absolute inset-0"
                />
              </motion.div>

              {/* Peso Total Box */}
              <motion.div 
                initial={{ scale: 0.95, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ type: "spring", stiffness: 300, damping: 25, delay: 0.1 }}
                className="-mx-6 bg-slate-900 pt-8 pb-8 px-6 text-white relative overflow-hidden shadow-[0_-15px_30px_0px_rgba(0,0,0,0.3)] z-20 mb-8 border-b-4 border-slate-950 rounded-t-xl"
              >
                 <div className="absolute top-1/2 -translate-y-1/2 right-0 p-4 opacity-10 pointer-events-none">
                   <Scale size={140} />
                 </div>
                 
                 <div className="relative z-10 flex flex-col items-center justify-center mb-8">
                    <span className="text-[11px] font-black text-slate-400 uppercase tracking-[0.2em] block mb-2">Farinha em Estoque</span>
                    <div className="flex items-baseline justify-center gap-1.5">
                      <span className="text-5xl font-black uppercase tracking-tight text-white drop-shadow-sm">{totalWeightStock.toLocaleString('pt-BR')}</span>
                      <span className="text-[16px] text-slate-500 font-bold uppercase ml-1">kg</span>
                    </div>
                 </div>

                 <div className="relative z-10 mt-auto">
                   <div className="flex justify-between items-end mb-2 px-1">
                      <span className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em]">Capacidade</span>
                      <span className="text-[12px] font-black text-amber-500">{occupancyPercent}%</span>
                   </div>
                   <div className="w-full bg-slate-800/80 rounded-none h-2 overflow-hidden shadow-inner border border-white/5">
                      <motion.div 
                        initial={{ width: 0 }}
                        animate={{ width: `${occupancyPercent}%` }}
                        transition={{ duration: 1.5, ease: "easeOut", delay: 0.2 }}
                        className="bg-slate-600 h-2 rounded-none" 
                      />
                   </div>
                 </div>
              </motion.div>
            </div>

            {/* Stock Summary Header */}
            <section className="space-y-4">
              
              <div className="grid gap-3">
                {[
                  { label: 'ESPECIAL', value: stock.special, color: 'text-blue-600', bg: 'bg-blue-50', img: 'https://i.ibb.co/3yYgYdjn/image.png' },
                  { label: 'COMUM', value: stock.common, color: 'text-emerald-600', bg: 'bg-emerald-50', img: 'https://i.ibb.co/r2PbxJbz/image.png' },
                  { label: 'INTEIRA', value: stock.whole, color: 'text-red-600', bg: 'bg-red-50', img: 'https://i.ibb.co/Xn0XLJM/image.png' },
                  { label: 'COLA', value: stock.glue, color: 'text-slate-900', bg: 'bg-slate-50', img: 'https://i.ibb.co/8LDzkhh8/image.png', isGlue: true },
                  { label: 'FARELO', value: stock.branStock || 0, color: 'text-amber-800', bg: 'bg-amber-50/30', img: 'https://i.ibb.co/chcGNGq8/image.png', isDirectKg: true },
                  { label: 'TRIGO', value: wheatStats.todayWeight || 0, color: 'text-amber-600', bg: 'bg-orange-50/50', img: 'https://i.ibb.co/DgbmXFt0/image.png', isDirectKg: true }
                ].filter(item => item.isDirectKg || item.value > 0).map((item) => (
                  <div key={item.label} className={`${item.bg} p-4 rounded-none border border-white shadow-sm flex items-center justify-between transition-all active:scale-[0.98]`}>
                    <div className="flex items-center gap-4">
                      <div className="w-14 h-14 bg-white rounded-none p-1 shadow-sm border border-slate-100/50">
                        <img src={item.img} alt={item.label} className="w-full h-full object-contain" style={{ imageRendering: '-webkit-optimize-contrast' }} />
                      </div>
                      <div>
                        <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{item.label}</p>
                        <p className={`text-xl font-black ${item.color}`}>
                          {item.isDirectKg ? item.value.toLocaleString('pt-BR') : item.value}
                          {item.isDirectKg && <span className="text-[10px] ml-1 opacity-60 uppercase">kg</span>}
                          {!item.isDirectKg && <span className="text-[10px] ml-1 opacity-50 uppercase">Begs</span>}
                        </p>
                      </div>
                    </div>
                    {!item.isDirectKg && (
                      <div className="text-right">
                        <p className="text-[9px] font-bold text-slate-400 uppercase">Kg Aprox.</p>
                        <p className="text-sm font-black text-slate-700">{formatWeight(calculateWeight(item.value, item.isGlue))}</p>
                      </div>
                    )}
                    {item.label === 'FARELO' && (
                      <div className="text-right space-y-1">
                        <p className="text-[9px] font-bold text-amber-800/40 uppercase tracking-tight">Ocupação Caixa</p>
                        <div className="flex items-center gap-2 justify-end">
                           <span className="text-[10px] font-black text-amber-700">{Math.max(0, Math.min(100, Math.round(((stock.branStock || 0) / 25000) * 100)))}%</span>
                           <div className="h-1 w-12 bg-amber-200/30 rounded-none overflow-hidden">
                             <motion.div 
                               initial={{ width: 0 }}
                               animate={{ width: `${Math.max(0, Math.min(100, ((stock.branStock || 0) / 25000) * 100))}%` }}
                               className="h-full bg-amber-500 rounded-none"
                             />
                           </div>
                        </div>
                      </div>
                    )}
                    {item.label === 'TRIGO' && (
                      <div className="text-right">
                        <p className="text-[9px] font-bold text-amber-600/60 uppercase">Entrada Hoje</p>
                        <div className="h-1 w-12 bg-amber-200 rounded-none mt-1 ml-auto" />
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </section>

            {/* Quick Actions */}
            <section className="pt-4">
              <h3 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-4">Ações Rápidas</h3>
              <div className="grid grid-cols-3 gap-3">
                <button 
                  onClick={() => setActiveTab('analyses')}
                  className="bg-white p-4 py-5 rounded-none border border-slate-100 shadow-sm flex flex-col items-center gap-2 active:scale-95 transition-all text-center"
                >
                  <div className="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-none flex items-center justify-center">
                    <ClipboardCheck size={20} />
                  </div>
                  <span className="text-[10px] font-black text-slate-800 uppercase tracking-widest leading-tight">Análises</span>
                </button>
                <button 
                  onClick={() => setActiveTab('extraction')}
                  className="bg-white p-4 py-5 rounded-none border border-slate-100 shadow-sm flex flex-col items-center gap-2 active:scale-95 transition-all text-center"
                >
                  <div className="w-10 h-10 bg-blue-50 text-blue-600 rounded-none flex items-center justify-center">
                    <TrendingUp size={20} />
                  </div>
                  <span className="text-[10px] font-black text-slate-800 uppercase tracking-widest leading-tight">Extração</span>
                </button>
                <button 
                  onClick={() => setActiveTab('validity')}
                  className="bg-white p-4 py-5 rounded-none border border-slate-100 shadow-sm flex flex-col items-center gap-2 active:scale-95 transition-all text-center"
                >
                  <div className="w-10 h-10 bg-amber-50 text-amber-800 rounded-none flex items-center justify-center">
                    <Calendar size={20} />
                  </div>
                  <span className="text-[10px] font-black text-slate-800 uppercase tracking-widest leading-tight">Validade</span>
                </button>
              </div>
            </section>
          </div>
        );
      case 'analyses':
        return (
          <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-500 pt-4">
            <div className="flex items-center gap-4 mb-4">
              <button onClick={() => setActiveTab('dashboard')} className="w-10 h-10 bg-white rounded-none shadow-sm flex items-center justify-center text-slate-400">
                <ChevronLeft size={20} />
              </button>
              <h2 className="text-xl font-black text-slate-800 uppercase tracking-tight">Qualidade</h2>
            </div>

            <div className="bg-white rounded-none p-8 shadow-sm border border-slate-100 space-y-8">
              <div className="grid grid-cols-3 gap-2">
                {[
                  { id: 'ESPECIAL', label: 'Especial', color: 'bg-blue-600', img: 'https://i.ibb.co/3yYgYdjn/image.png' },
                  { id: 'COMUM', label: 'Comum', color: 'bg-emerald-600', img: 'https://i.ibb.co/r2PbxJbz/image.png' },
                  { id: 'INTEIRA', label: 'Inteira', color: 'bg-red-600', img: 'https://i.ibb.co/Xn0XLJM/image.png' },
                  { id: 'COLA', label: 'Cola', color: 'bg-slate-900', img: 'https://i.ibb.co/8LDzkhh8/image.png' },
                  { id: 'FARELO', label: 'Farelo', color: 'bg-amber-800', img: 'https://i.ibb.co/chcGNGq8/image.png' },
                  { id: 'TRIGO', label: 'Trigo', color: 'bg-amber-600', img: 'https://i.ibb.co/DgbmXFt0/image.png' }
                ].map(t => (
                  <button 
                    key={t.id}
                    onClick={() => setAnalysisForm({ ...analysisForm, type: t.id })}
                    className={`p-3 rounded-none border-2 flex flex-col items-center gap-2 transition-all ${analysisForm.type === t.id ? `${t.color} border-transparent text-white shadow-lg scale-105` : 'bg-slate-50 border-slate-100 text-slate-400'}`}
                  >
                    <img src={t.img} className="w-8 h-8 object-contain" style={{ imageRendering: '-webkit-optimize-contrast' }} />
                    <span className="text-[8px] font-black uppercase tracking-widest">{t.label}</span>
                  </button>
                ))}
              </div>

              <div className={`grid ${analysisForm.type === 'FARELO' ? 'grid-cols-1' : 'grid-cols-2'} gap-4`}>
                {analysisForm.type !== 'FARELO' && (
                  <div className="space-y-2 text-center">
                    <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
                      {analysisForm.type === 'TRIGO' ? 'PH' : 'Cor (L*)'}
                    </label>
                    <input 
                      type="text"
                      inputMode="decimal"
                      value={analysisForm.color}
                      onChange={(e) => setAnalysisForm({ ...analysisForm, color: analysisForm.type === 'TRIGO' ? e.target.value.replace(/\D/g, '').slice(0, 2) : maskBrazilian(e.target.value) })}
                      placeholder="00.0"
                      className="w-full bg-slate-50 border border-slate-200 rounded-none p-6 text-3xl font-[900] text-center text-slate-800 focus:border-blue-500 outline-none transition-all"
                    />
                  </div>
                )}
                <div className="space-y-2 text-center">
                  <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Umidade (%)</label>
                  <input 
                    type="text"
                    inputMode="decimal"
                    value={analysisForm.humidity}
                    onChange={(e) => setAnalysisForm({ ...analysisForm, humidity: maskHumidity(e.target.value) })}
                    placeholder="00.0"
                    className="w-full bg-slate-50 border border-slate-200 rounded-none p-6 text-3xl font-[900] text-center text-slate-800 focus:border-blue-500 outline-none transition-all"
                  />
                </div>
              </div>

              <button 
                onClick={handleSaveAnalysis}
                disabled={isSaving || !analysisForm.humidity || (analysisForm.type !== 'FARELO' && !analysisForm.color)}
                className="w-full bg-slate-900 text-white font-black py-5 rounded-none shadow-xl active:scale-95 transition-all uppercase text-xs tracking-widest flex items-center justify-center gap-3 disabled:opacity-50"
              >
                {isSaving ? <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-none animate-spin" /> : <Save size={20} />}
                Salvar Análise
              </button>
            </div>
          </div>
        );
      case 'extraction':
        if (showExtractionResults) {
          const chartData = [
            { name: 'Farinha', value: extractionResults.totalFlour, color: '#2563eb' },
            { name: 'Farelo', value: extractionResults.bran, color: '#92400e' }
          ].filter(d => d.value > 0);

          return (
            <div className="animate-in fade-in zoom-in-95 duration-500 pt-4 space-y-6 pb-20">
              <div className="flex items-center gap-4">
                <button onClick={() => setShowExtractionResults(false)} className="w-10 h-10 bg-white rounded-none shadow-sm flex items-center justify-center text-slate-400">
                  <ChevronLeft size={20} />
                </button>
                <h2 className="text-xl font-black text-slate-800 uppercase tracking-tight">Análise Industrial</h2>
              </div>

              {/* Wrapped Report Element for Crisp Capture */}
              <div id="extraction-report-element" className="space-y-6 bg-slate-50/10 p-1">
              {/* Analytics Section - High Performance Design */}
              <div className="bg-white rounded-none pt-4 pb-8 px-8 shadow-sm border border-slate-100">
                <div className="relative w-full h-[260px] flex flex-col items-center justify-center mb-8 mt-4">
                  <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                      <Pie
                        data={[
                          { name: 'Especial', value: extractionResults.special, color: '#2563eb' },
                          { name: 'Comum', value: extractionResults.common, color: '#059669' },
                          { name: 'Inteira', value: extractionResults.whole, color: '#dc2626' },
                          { name: 'Cola', value: extractionResults.glue, color: '#0f172a' },
                          { name: 'Farelo', value: extractionResults.bran, color: '#92400e' }
                        ].filter(d => d.value > 0)}
                        innerRadius="75%"
                        outerRadius="95%"
                        paddingAngle={4}
                        dataKey="value"
                        stroke="none"
                      >
                        {[
                          { name: 'Especial', value: extractionResults.special, color: '#2563eb' },
                          { name: 'Comum', value: extractionResults.common, color: '#059669' },
                          { name: 'Inteira', value: extractionResults.whole, color: '#dc2626' },
                          { name: 'Cola', value: extractionResults.glue, color: '#0f172a' },
                          { name: 'Farelo', value: extractionResults.bran, color: '#92400e' }
                        ].filter(d => d.value > 0).map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.color} />
                        ))}
                      </Pie>
                    </PieChart>
                  </ResponsiveContainer>
                  
                  {/* High Intensity Center Label */}
                  <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none mt-2">
                    <span className="text-xs font-black text-slate-400 uppercase tracking-[0.3em] mb-1">Extração</span>
                    <div className="flex items-baseline gap-1">
                      <span className="text-5xl font-[900] text-slate-900 tabular-nums">
                        {(extractionResults.extractionPercent || 0).toFixed(1).replace('.', ',')}
                      </span>
                      <span className="text-2xl font-black text-blue-600">%</span>
                    </div>
                  </div>
                </div>

                <div className="space-y-2">
                  {/* Highlighted Wheat Input */}
                  <div className="bg-slate-900 -mx-8 px-8 py-5 mb-2 flex justify-between items-center border-y border-slate-800">
                    <div className="flex flex-col text-left">
                      <span className="text-xs font-black text-amber-500 uppercase tracking-widest">Trigo Por Hora</span>
                    </div>
                    <div className="text-right">
                      <span className="text-3xl font-[900] text-white">{extractionResults.totalProducts.toLocaleString('pt-BR')}</span>
                      <span className="text-sm font-black text-amber-500 ml-1.5">kg/h</span>
                    </div>
                  </div>

                  {/* Highlighted Flour Output */}
                  <div className="bg-slate-900 -mx-8 px-8 py-5 mb-8 mt-0 flex justify-between items-center">
                    <div className="flex flex-col text-left">
                      <span className="text-xs font-black text-sky-400 uppercase tracking-widest">Farinha Por Hora</span>
                      <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mt-0.5">Volume Total</span>
                    </div>
                    <div className="text-right">
                      <span className="text-3xl font-[900] text-white">{extractionResults.totalFlour.toLocaleString('pt-BR')}</span>
                      <span className="text-sm font-black text-sky-500 ml-1.5">kg/h</span>
                    </div>
                  </div>

                  <div className="space-y-3">
                    {[
                      { label: 'Farinha Especial', value: extractionResults.special, color: 'text-blue-700' },
                      { label: 'Farinha Comum', value: extractionResults.common, color: 'text-emerald-600' },
                      { label: 'Farinha Inteira', value: extractionResults.whole, color: 'text-red-600' },
                      { label: 'Farinha Cola', value: extractionResults.glue, color: 'text-slate-900' },
                      { label: 'Farelo de Trigo', value: extractionResults.bran, color: 'text-amber-800' }
                    ].filter(i => (i.value || 0) > 0).map(item => {
                      const perc = (item.value / extractionResults.totalProducts) * 100;
                      return (
                        <div key={item.label} className="flex justify-between items-center group border-b border-slate-200 pb-3">
                          <div className="flex flex-col text-left">
                            <span className={`text-base font-[900] uppercase tracking-tight ${item.color}`}>{item.label}</span>
                            <span className="text-xs font-black text-slate-500 uppercase tracking-widest mt-0.5">{perc.toFixed(1)}% do trigo</span>
                          </div>
                          <div className="text-right">
                            <span className={`text-xl font-black ${item.color}`}>{item.value.toLocaleString('pt-BR')} <span className="text-xs opacity-50 ml-0.5">kg</span></span>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                  
                  <div className="pt-6 mt-4 border-t-2 border-slate-900 flex justify-between items-center">
                    <div className="flex flex-col text-left">
                      <span className="text-xs font-black text-slate-400 uppercase tracking-widest">Total Produzido</span>
                    </div>
                    <span className="text-3xl font-[900] text-slate-900">{extractionResults.totalProducts.toLocaleString('pt-BR')} <span className="text-xl">kg</span></span>
                  </div>
                </div>
              </div>

              </div>
              <div className="space-y-3">
                <div className="grid grid-cols-2 gap-3 pt-2">
                  <button 
                    onClick={handleSaveExtraction}
                    disabled={isSaving}
                    className="w-full bg-blue-600 text-white font-black py-4 rounded-none shadow-lg shadow-blue-100 active:scale-95 transition-all text-xs tracking-widest flex items-center justify-center gap-2"
                  >
                    {isSaving ? <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-none animate-spin" /> : <Save size={18} />}
                    SALVAR
                  </button>
                  <button 
                    onClick={() => setShowExtractionResults(false)}
                    className="w-full bg-slate-100 text-slate-500 font-black py-4 rounded-none border border-slate-200 active:scale-95 transition-all text-xs tracking-widest uppercase"
                  >
                    NOVO
                  </button>
                </div>

              </div>
            </div>
          );
        }

        return (
          <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-500 pt-4 pb-24">
            {/* Title Header */}
            <div className="flex items-center gap-4 mb-4">
              <button onClick={() => setActiveTab('dashboard')} className="w-10 h-10 bg-white rounded-none shadow-sm flex items-center justify-center text-slate-400">
                <ChevronLeft size={20} />
              </button>
              <h2 className="text-xl font-black text-slate-800 uppercase tracking-tight">Extração</h2>
            </div>

            {/* Segment Selector */}
            <div className="flex bg-slate-100 p-1 rounded-none border border-slate-200">
              <button
                onClick={() => setExtractionSubTab('simulator')}
                className={`flex-1 py-3 text-center text-xs font-black uppercase tracking-wider transition-all duration-200 ${
                  extractionSubTab === 'simulator'
                    ? 'bg-white text-slate-900 shadow-sm font-black'
                    : 'text-slate-400 hover:text-slate-600'
                }`}
              >
                Simulador Manual
              </button>
              <button
                onClick={() => setExtractionSubTab('realtime')}
                className={`flex-1 py-3 text-center text-xs font-black uppercase tracking-wider transition-all duration-200 ${
                  extractionSubTab === 'realtime'
                    ? 'bg-white text-slate-900 shadow-sm font-black'
                    : 'text-slate-400 hover:text-slate-600'
                }`}
              >
                Lote em Vigor
              </button>
            </div>

            {/* Segment Contents */}
            {extractionSubTab === 'realtime' ? (
              <div className="space-y-6">
                {!activeBatch ? (
                  <div className="bg-white rounded-none p-12 text-center border border-slate-100 flex flex-col items-center justify-center">
                    <AlertTriangle size={40} className="text-amber-500 mb-4" />
                    <h3 className="text-sm font-black text-slate-800 uppercase tracking-wider">Nenhum lote em vigor</h3>
                    <p className="text-[10px] font-medium text-slate-400 uppercase tracking-widest mt-2 max-w-[240px]">
                      Não há nenhum lote aberto no momento para exibir métricas em tempo real.
                    </p>
                  </div>
                ) : (
                  <>
                    {/* Real-time Hero Card */}
                    <div className="bg-slate-900 rounded-none p-8 text-center relative overflow-hidden border border-slate-800 shadow-2xl">
                      <div className="absolute top-0 right-0 p-4 opacity-5">
                        <Activity size={100} className="text-white" />
                      </div>
                      
                      <p className="text-blue-400 text-[10px] font-black uppercase tracking-[0.4em] mb-3 relative z-10">Rendimento Estimado</p>
                      <h3 className="text-lg font-[900] text-white uppercase tracking-tight mb-4 relative z-10 leading-none">{activeBatch.name}</h3>
                      <div className="flex items-baseline justify-center gap-2 mb-6 relative z-10">
                        <span className="text-7xl font-black text-white">{activeBatchMetrics ? activeBatchMetrics.actualExtractionRate.toFixed(2).replace('.', ',') : '0,00'}</span>
                        <span className="text-2xl font-black text-blue-500">%</span>
                      </div>

                      <div className="grid grid-cols-2 gap-4 relative z-10 border-t border-white/5 pt-6">
                        <div className="text-center border-r border-white/5">
                          <p className="text-[8px] font-black text-slate-500 uppercase tracking-widest mb-1">Total Moído (Trigo)</p>
                          <p className="text-lg font-black text-white">{activeBatchMetrics ? activeBatchMetrics.totalWheat.toLocaleString('pt-BR') : '0'} <span className="text-[10px] text-amber-500">kg</span></p>
                        </div>
                        <div className="text-center">
                          <p className="text-[8px] font-black text-slate-500 uppercase tracking-widest mb-1">Total Farinha Produzida</p>
                          <p className="text-lg font-black text-white">{activeBatchMetrics ? activeBatchMetrics.estimatedTotalFlour.toLocaleString('pt-BR') : '0'} <span className="text-[10px] text-emerald-500">kg</span></p>
                        </div>
                      </div>
                    </div>

                    {/* Ratios Breakdown List */}
                    <div className="space-y-4">
                      <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-1">
                        Tipos de Farinha s/ Trigo Moído
                      </h3>

                      <div className="grid gap-3">
                        {[
                          { 
                            label: 'Farinha Especial', 
                            bags: activeBatchMetrics?.specialBags || 0,
                            kg: activeBatchMetrics?.totalSpecialFlourKg || 0,
                            perc: activeBatchMetrics?.specialPctOfWheat || 0,
                            color: 'text-blue-500', 
                            bg: 'bg-blue-50/50', 
                            border: 'border-blue-100',
                            img: 'https://i.ibb.co/3yYgYdjn/image.png' 
                          },
                          { 
                            label: 'Farinha Comum', 
                            bags: activeBatchMetrics?.commonBags || 0,
                            kg: activeBatchMetrics?.totalCommonFlourKg || 0,
                            perc: activeBatchMetrics?.commonPctOfWheat || 0,
                            color: 'text-emerald-500', 
                            bg: 'bg-emerald-50/50', 
                            border: 'border-emerald-100',
                            img: 'https://i.ibb.co/r2PbxJbz/image.png' 
                          },
                          { 
                            label: 'Farinha Inteira', 
                            bags: activeBatchMetrics?.wholeBags || 0,
                            kg: activeBatchMetrics?.totalWholeFlourKg || 0,
                            perc: activeBatchMetrics?.wholePctOfWheat || 0,
                            color: 'text-red-500', 
                            bg: 'bg-red-50/50', 
                            border: 'border-red-100',
                            img: 'https://i.ibb.co/Xn0XLJM/image.png' 
                          },
                          { 
                            label: 'Farinha Cola', 
                            bags: activeBatchMetrics?.glueBags || 0,
                            kg: activeBatchMetrics?.totalGlueFlourKg || 0,
                            perc: activeBatchMetrics?.gluePctOfWheat || 0,
                            color: 'text-slate-900', 
                            bg: 'bg-slate-50/50', 
                            border: 'border-slate-200/50',
                            img: 'https://i.ibb.co/8LDzkhh8/image.png' 
                          },
                          { 
                            label: 'Farelo de Trigo', 
                            bags: 0,
                            kg: activeBatchMetrics?.estimatedTotalBran || 0,
                            perc: activeBatchMetrics && activeBatchMetrics.totalWheat > 0 ? (activeBatchMetrics.estimatedTotalBran / activeBatchMetrics.totalWheat) * 100 : 0,
                            color: 'text-amber-800', 
                            bg: 'bg-amber-50/30', 
                            border: 'border-amber-200/50',
                            img: 'https://i.ibb.co/chcGNGq8/image.png',
                            isDirectKg: true
                          }
                        ].map((item) => (
                          <div key={item.label} className={`p-4 rounded-none border ${item.border} ${item.bg} flex items-center justify-between`}>
                            <div className="flex items-center gap-4">
                              <div className="w-12 h-12 bg-white rounded-none p-1 shadow-xs border border-slate-100/50">
                                <img src={item.img} referrerPolicy="no-referrer" alt={item.label} className="w-full h-full object-contain" style={{ imageRendering: '-webkit-optimize-contrast' }} />
                              </div>
                              <div>
                                <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{item.label}</p>
                                <p className={`text-base font-black ${item.color}`}>
                                  {item.kg.toLocaleString('pt-BR')} <span className="text-[10px] uppercase font-bold opacity-60">kg</span>
                                </p>
                              </div>
                            </div>
                            <div className="text-right">
                              <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest leading-none">% do Trigo</p>
                              <p className="text-base font-black text-slate-800 mt-1">{item.perc.toFixed(2).replace('.', ',')}%</p>
                              {!item.isDirectKg && <span className="text-[9px] font-bold text-slate-450 uppercase block">{item.bags} Bags</span>}
                              {item.isDirectKg && <span className="text-[9px] font-bold text-slate-400 uppercase block">Subproduto</span>}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </>
                )}
              </div>
            ) : (
              <div className="bg-white rounded-none p-8 shadow-sm border border-slate-100 space-y-6">
                <div className="grid grid-cols-2 gap-4">
                  {[
                    { id: 'special', label: 'Especial', color: 'focus:border-blue-500' },
                    { id: 'common', label: 'Comum', color: 'focus:border-emerald-500' },
                    { id: 'whole', label: 'Inteira', color: 'focus:border-red-500' },
                    { id: 'glue', label: 'Cola', color: 'focus:border-slate-900' },
                    { id: 'bran', label: 'Farelo', color: 'focus:border-amber-800', full: true }
                  ].map(field => (
                    <div key={field.id} className={field.full ? 'col-span-2' : ''}>
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1 ml-1 block">{field.label}</label>
                      <input 
                        type="text"
                        inputMode="decimal"
                        value={extractionForm[field.id as keyof typeof extractionForm]}
                        onChange={(e) => setExtractionForm({ ...extractionForm, [field.id]: maskBrazilian(e.target.value) })}
                        placeholder="0,00"
                        className={`w-full bg-slate-50 border border-slate-200 rounded-none p-6 text-3xl font-[900] text-center text-slate-800 outline-none transition-all ${field.color}`}
                      />
                    </div>
                  ))}
                </div>

                <button 
                  onClick={() => setShowExtractionResults(true)}
                  className="w-full bg-slate-900 text-white font-black py-5 rounded-none shadow-xl active:scale-95 transition-all uppercase text-xs tracking-widest flex items-center justify-center gap-3"
                >
                  <Zap size={20} fill="currentColor" />
                  DASHBOARD ANALÍTICO
                </button>
              </div>
            )}
          </div>
        );
      case 'wheat':
        return (
          <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-500 pt-4 pb-20">
            <div className="flex items-center gap-4 mb-4">
              <button onClick={() => setActiveTab('dashboard')} className="w-10 h-10 bg-white rounded-none shadow-sm flex items-center justify-center text-slate-400">
                <ChevronLeft size={20} />
              </button>
              <h2 className="text-xl font-black text-slate-800 uppercase tracking-tight">Cargas de Trigo</h2>
            </div>

            {/* Quality Summary Header */}
            <div className="bg-slate-900 rounded-none p-6 shadow-xl border border-slate-800 relative overflow-hidden">
               <div className="absolute top-0 right-0 p-4 opacity-10">
                 <Truck size={60} className="text-white" />
               </div>
               <div className="relative z-10 space-y-6">
                 <div>
                   <p className="text-slate-500 text-[10px] font-black uppercase tracking-[0.2em] mb-1">Total Descarregado Hoje</p>
                   <p className="text-3xl font-black text-white tabular-nums">
                     {wheatStats.todayWeight.toLocaleString('pt-BR')} <span className="text-xs text-slate-500">kg</span>
                   </p>
                 </div>

                 <div className="grid grid-cols-2 gap-4">
                   <div className="bg-white/5 rounded-none p-4 border border-white/5 flex items-center gap-3">
                     <div className="w-10 h-10 rounded-none bg-blue-500/20 text-blue-400 flex items-center justify-center">
                        <Droplets size={18} />
                     </div>
                     <div>
                        <p className="text-[8px] font-black text-slate-500 uppercase tracking-widest">Média UMI</p>
                        <p className="text-sm font-black text-white">
                          {wheatStats.avgMoisture.toFixed(1).replace('.', ',')} <span className="text-[10px] opacity-50">%</span>
                        </p>
                     </div>
                   </div>
                   <div className="bg-white/5 rounded-none p-4 border border-white/5 flex items-center gap-3">
                     <div className="w-10 h-10 rounded-none bg-amber-500/20 text-amber-400 flex items-center justify-center">
                        <Scale size={18} />
                     </div>
                     <div>
                        <p className="text-[8px] font-black text-slate-500 uppercase tracking-widest">Média PH</p>
                        <p className="text-sm font-black text-white">
                          {Math.round(wheatStats.avgPh)}
                        </p>
                     </div>
                   </div>
                 </div>
               </div>
            </div>

            {/* Notification and Loud Sound activation controls for operators */}
            <div className="bg-white p-5 rounded-none border border-slate-100 shadow-sm flex flex-col gap-3 text-left">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="w-9 h-9 bg-amber-50 rounded-none flex items-center justify-center text-amber-600">
                    <Zap size={18} />
                  </div>
                  <div>
                    <h3 className="text-xs font-black text-slate-800 uppercase tracking-wider">Avisos de Descarga</h3>
                    <p className="text-[9px] font-bold text-slate-400 uppercase">Som Alto + Notificações no Celular</p>
                  </div>
                </div>
                <button
                  onClick={async () => {
                    if (typeof Notification !== 'undefined') {
                      const permission = await Notification.requestPermission();
                      if (permission === 'granted') {
                        setAlertsEnabled(true);
                        localStorage.setItem('mocca_wheat_alerts_enabled', 'true');
                        testAlert();
                      } else {
                        alert("Notificações desativadas ou bloqueadas. Ative nas configurações do Chrome/Safari para receber avisos de trigo!");
                      }
                    } else {
                      testAlert();
                    }
                  }}
                  className={`px-4 py-2 text-[10px] font-black uppercase tracking-widest border transition-all ${
                    typeof Notification !== 'undefined' && Notification.permission === 'granted'
                      ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                      : 'bg-amber-600 text-white border-amber-600 active:scale-95'
                  }`}
                >
                  {typeof Notification !== 'undefined' && Notification.permission === 'granted'
                    ? 'ATIVADO'
                    : 'ATIVAR ALERTA'}
                </button>
              </div>

              <div className="flex gap-2 pt-2 border-t border-slate-50">
                <button
                  type="button"
                  onClick={testAlert}
                  className="flex-1 bg-slate-50 hover:bg-slate-100 text-slate-700 p-2.5 text-[9px] font-black uppercase tracking-widest border border-slate-200 text-center flex items-center justify-center gap-1.5 active:scale-95 transition-all"
                >
                  <Clock size={12} /> Testar Sinal Sonoro e Alerta
                </button>
              </div>
            </div>

            <div className="space-y-4">
              <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Lançamentos de Hoje</h3>
              <div className="grid gap-4">
                {wheatStats.todayLoads.length > 0 ? wheatStats.todayLoads.map(load => (
                  <div key={load.id} className="bg-white p-5 rounded-none border border-slate-100 shadow-sm relative overflow-hidden group active:scale-95 transition-all">
                    <div className="flex justify-between items-start mb-4">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 bg-blue-50 rounded-none flex items-center justify-center text-blue-600">
                          <Truck size={20} />
                        </div>
                        <div>
                          <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{load.driver || 'Não informado'}</p>
                          <h4 className="text-xs font-black text-slate-800 uppercase tabular-nums">{load.entity || 'Fornecedor'}</h4>
                        </div>
                      </div>
                      <div className="text-right">
                         <p className="text-lg font-black text-slate-900 leading-none">{(load.finalWeight || 0).toLocaleString()} <span className="text-[10px] text-slate-400 uppercase">kg</span></p>
                         <p className="text-[8px] font-bold text-slate-400 uppercase mt-1">Peso Final</p>
                      </div>
                    </div>
                    
                    <div className="flex gap-2">
                       <div className="flex-grow bg-blue-50/50 rounded-none p-3 border border-blue-100/30 flex justify-between items-center transition-colors group-hover:bg-blue-50">
                          <span className="text-[8px] font-black text-blue-800 uppercase tracking-widest">Umidade</span>
                          <span className="text-xs font-black text-blue-600">{(load.moisture || 0).toFixed(1)}%</span>
                       </div>
                       <div className="flex-grow bg-amber-50/50 rounded-none p-3 border border-amber-100/30 flex justify-between items-center transition-colors group-hover:bg-amber-50">
                          <span className="text-[8px] font-black text-amber-800 uppercase tracking-widest">PH</span>
                          <span className="text-xs font-black text-amber-600">{(load.ph || 0).toFixed(0)}</span>
                       </div>
                    </div>
                  </div>
                )) : (
                  <div className="py-12 flex flex-col items-center justify-center text-slate-300">
                    <Truck size={40} strokeWidth={1.5} className="mb-4 opacity-20" />
                    <p className="text-[10px] font-black uppercase tracking-[0.2em] italic">Nenhuma carga hoje</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        );
      case 'validity':
        const validityDays = validityType === 'farinha' ? 120 : 90;
        const parsedProdDate = (() => {
          if (!prodDate) return new Date();
          const [year, month, day] = prodDate.split('-').map(Number);
          return new Date(year, month - 1, day);
        })();

        const expirationDate = (() => {
          const exp = new Date(parsedProdDate);
          exp.setDate(exp.getDate() + validityDays);
          return exp;
        })();

        const formatDateBR = (date: Date): string => {
          const day = String(date.getDate()).padStart(2, '0');
          const month = String(date.getMonth() + 1).padStart(2, '0');
          const year = date.getFullYear();
          return `${day}/${month}/${year}`;
        };

        const parsedProdDateStr = formatDateBR(parsedProdDate);
        const expirationDateStr = formatDateBR(expirationDate);

        return (
          <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-500 pt-4 pb-20 text-left">
            <div className="flex items-center gap-4 mb-4">
              <button onClick={() => setActiveTab('dashboard')} className="w-10 h-10 bg-white rounded-none shadow-sm flex items-center justify-center text-slate-400">
                <ChevronLeft size={20} />
              </button>
              <h2 className="text-xl font-black text-slate-800 uppercase tracking-tight">Calculadora de Validade</h2>
            </div>

            {/* Product Type Selection */}
            <div className="grid grid-cols-2 gap-4">
              <button
                onClick={() => setValidityType('farinha')}
                className={`p-5 rounded-none border-2 flex flex-col items-center gap-4 transition-all ${
                  validityType === 'farinha'
                    ? 'border-blue-600 bg-blue-50/50 text-blue-700 shadow-md scale-[1.02]'
                    : 'bg-white border-slate-100 text-slate-400 hover:text-slate-600'
                }`}
              >
                <div className={`w-24 h-24 rounded-none flex items-center justify-center border-2 p-2.5 ${
                  validityType === 'farinha' ? 'bg-white border-blue-200 shadow-sm' : 'bg-slate-50 border-slate-200'
                }`}>
                  <img 
                    src="https://i.ibb.co/3yYgYdjn/image.png" 
                    alt="Farinha" 
                    className="w-full h-full object-contain mix-blend-multiply" 
                    style={{ imageRendering: '-webkit-optimize-contrast', transform: 'scale(1.05)' }} 
                    referrerPolicy="no-referrer"
                  />
                </div>
                <div className="text-center">
                  <span className="text-sm font-black uppercase tracking-widest block">FARINHA</span>
                  <span className="text-xs font-bold text-blue-600/80 mt-0.5 block">120 DIAS</span>
                </div>
              </button>

              <button
                onClick={() => setValidityType('farelo')}
                className={`p-5 rounded-none border-2 flex flex-col items-center gap-4 transition-all ${
                  validityType === 'farelo'
                    ? 'border-amber-800 bg-amber-50/20 text-amber-950 shadow-md scale-[1.02]'
                    : 'bg-white border-slate-100 text-slate-400 hover:text-slate-600'
                }`}
              >
                <div className={`w-24 h-24 rounded-none flex items-center justify-center border-2 p-2.5 ${
                  validityType === 'farelo' ? 'bg-white border-amber-200 shadow-sm' : 'bg-slate-50 border-slate-200'
                }`}>
                  <img 
                    src="https://i.ibb.co/chcGNGq8/image.png" 
                    alt="Farelo" 
                    className="w-full h-full object-contain mix-blend-multiply" 
                    style={{ imageRendering: '-webkit-optimize-contrast', transform: 'scale(1.05)' }} 
                    referrerPolicy="no-referrer"
                  />
                </div>
                <div className="text-center">
                  <span className="text-sm font-black uppercase tracking-widest block">FARELO</span>
                  <span className="text-xs font-bold text-amber-800/80 mt-0.5 block">90 DIAS</span>
                </div>
              </button>
            </div>

            {/* Date Input Card */}
            <div className="bg-white rounded-none p-6 shadow-sm border border-slate-100 space-y-4 text-left">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block">
                Data do Dia / Fabricação
              </label>
              <input
                type="date"
                value={prodDate}
                onChange={(e) => setProdDate(e.target.value)}
                className="w-full bg-slate-50 border border-slate-200 rounded-none p-6 text-2xl font-black text-center text-slate-800 focus:border-blue-500 outline-none transition-all"
              />
              <div className="flex justify-between text-[10px] font-bold text-slate-400 uppercase">
                <span>Calculando com base em:</span>
                <span className="text-slate-700 underline cursor-pointer" onClick={() => {
                  const today = new Date();
                  const yyyy = today.getFullYear();
                  const mm = String(today.getMonth() + 1).padStart(2, '0');
                  const dd = String(today.getDate()).padStart(2, '0');
                  setProdDate(`${yyyy}-${mm}-${dd}`);
                }}>Voltar para Hoje</span>
              </div>
            </div>

            {/* Result Visual Card */}
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              key={`${validityType}-${prodDate}`}
              className="bg-slate-900 rounded-none p-8 text-center relative overflow-hidden border border-slate-800 shadow-2xl"
            >
              <div className="absolute top-0 right-0 p-4 opacity-5">
                <Clock size={100} className="text-white" />
              </div>
              
              <p className="text-amber-500 text-[10px] font-black uppercase tracking-[0.4em] mb-4 relative z-10">
                Resultado do Prazo
              </p>

              <div className="space-y-1 mb-6 relative z-10">
                <p className="text-slate-400 text-[10px] font-black tracking-widest uppercase">PRODUTO COM VALIDADE ATÉ:</p>
                <div className="flex items-baseline justify-center gap-1.5 mt-2">
                  <span className="text-4xl font-[950] text-white tracking-widest font-mono">{expirationDateStr}</span>
                </div>
              </div>

              <div className="border-t border-white/5 pt-6 text-center space-y-2">
                <p className="text-xs text-slate-300 leading-relaxed">
                  Período de conservação de <span className="font-black text-white">{validityDays} dias</span> a partir de <span className="font-bold text-white">{parsedProdDateStr}</span>.
                </p>
                <div className="inline-block bg-white/5 px-3 py-1 rounded-none border border-white/10 text-[9px] font-black text-slate-400 uppercase tracking-widest mt-2">
                  Parâmetro Oficial de Qualidade MOCCA
                </div>
              </div>
            </motion.div>
          </div>
        );
    }
  };

  return (
    <div className="min-h-screen bg-[#FDFDFD] flex flex-col max-w-[430px] mx-auto shadow-[0_0_100px_rgba(0,0,0,0.05)] relative overflow-hidden">
      {/* Background Decorative Element */}
      <div className="absolute top-0 left-0 right-0 h-64 bg-gradient-to-b from-blue-50/30 to-transparent pointer-events-none" />

      {/* Main Content Scrollable Area */}
      <main className="flex-grow overflow-y-auto px-6 pb-32 relative z-10 scrollbar-hide">
        {renderTabContent()}
      </main>

      {/* Bottom Navigation */}
      <nav className="sticky bottom-0 left-0 right-0 w-full px-4 py-6 pb-10 bg-white/80 backdrop-blur-2xl border-t border-slate-100/50 flex justify-around items-center z-[100]">
        {[
          { id: 'dashboard', icon: <LayoutGrid size={20} />, label: 'Dashboard' },
          { id: 'analyses', icon: <Microscope size={20} />, label: 'Análises' },
          { id: 'extraction', icon: <TrendingUp size={20} />, label: 'Produção' },
          { id: 'wheat', icon: <Truck size={20} />, label: 'Cargas' },
          { id: 'validity', icon: <Calendar size={20} />, label: 'Validade' }
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as MobileTab)}
            className={`flex flex-col items-center gap-1 transition-all ${activeTab === tab.id ? 'text-blue-600 scale-105' : 'text-slate-400'}`}
          >
            <div className={`p-2 rounded-none transition-colors ${activeTab === tab.id ? 'bg-blue-50 shadow-sm' : ''}`}>
              {tab.icon}
            </div>
            <span className="text-[7px] font-black uppercase tracking-[0.2em]">{tab.label}</span>
            {activeTab === tab.id && (
              <motion.div layoutId="nav-pill" className="h-1 w-1 bg-mocca-gold rounded-none mt-1" />
            )}
          </button>
        ))}
      </nav>

      {/* Success Success Overlay */}
      <AnimatePresence>
        {showSuccess && (
          <motion.div 
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9 }}
            className="absolute inset-0 z-[200] flex items-center justify-center p-8 bg-white/50 backdrop-blur-sm"
          >
            <div className="bg-white rounded-none p-10 text-center shadow-2xl border border-slate-100 flex flex-col items-center">
              <div className="w-20 h-20 bg-emerald-50 text-emerald-600 rounded-none flex items-center justify-center mb-6 shadow-sm border border-emerald-100">
                <CheckCircle2 size={40} />
              </div>
              <h2 className="text-xl font-black text-slate-900 uppercase tracking-tight mb-2">Sucesso!</h2>
              <p className="text-slate-400 text-[10px] font-black uppercase tracking-widest">Seu registro foi enviado para o moinho.</p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
